SistemAcademico/Controllers/AsignaturaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemAcademico.Filters;
using SistemAcademico.Models;
using System.Collections.Generic;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class AsignaturaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoAsignatura()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoAsignatura", Code.Asignatura.ConsultarAsignatura(null));
        }

        public IActionResult AgregarAsignatura()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            ViewBag.Curso = Code.Curso.ConsultarCatalogoCurso();
            return PartialView("AgregarAsignatura");
        }

        public IActionResult GrabarAsignatura(AsignaturaModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Asignatura.GrabarAsignatura(model);
            return View("Index");
        }

        public IActionResult EditarAsignatura(int idAsignatura)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            var asignatura = Code.Asignatura.ConsultarAsignaturaPorId(idAsignatura);
            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            ViewBag.Curso = Code.Curso.ConsultarCatalogoCurso();
            return PartialView("EditarAsignatura", asignatura);
        }

        public IActionResult ActualizarAsignatura(AsignaturaModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Asignatura.ActualizarAsignatura(model);
            return View();
        }

        public IActionResult EliminarAsignatura(int idAsignatura)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Asignatura.EliminarAsignatura(idAsignatura);
            return MantenimientoAsignatura();
        }
    }
}

SistemAcademico/Views/Asignatura/AgregarAsignatura.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>

@model SistemAcademico.Models.AsignaturaModel

        <div class="row">
            <div class="col-lg-12">
                <label asp-for="Nombre" class="col-lg-4"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <label asp-for="Descripcion" class="col-lg-4"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>

        <div class="modal-footer">
            <button class="btn btn-sm btn-success" id="btnGrabarAsignatura">
                <i class="glyphicon glyphicon-refresh"></i> Grabar
            </button>
            <button class="btn btn-sm btn-danger" id="btnCerrar" data-dismiss="modal" aria-hidden="true">
                <i class="glyphicon glyphicon-remove"></i> Cerrar
            </button>
        </div>
    </div>

<script>

    function modeloAsignatura()
    {
        var modelo =
        {
            Nombre: $('#Nombre').val(),
            Descripcion: $('#Descripcion').val(),
        };
        return modelo;
    }

    //function validarDatos() {
    //    var model = modeloProfesor();
    //    if (model.Nombres === "") {
    //        alert("Ingrese Nombre");
    //        return false;
    //    }

    //    if (model.Apellidos === "") {
    //        alert("Ingrese Apellidos");
    //        return false;
    //    }

    //    if (model.Cedula === "") {
    //        alert("Ingrese Cedula");
    //        return false;
    //    }
    //    return true;
    //};

    $("#btnGrabarAsignatura").click(function () {

        var model = modeloAsignatura();

        //datos = validarDatos();
        //if (!datos) {
        //    return false;
        //}

        $.ajax(
            {
                cache: false,
                type: 'POST',
                url: '@Url.Action("GrabarAsignatura", "Asignatura")',
                data: model,
                success: function () {
                    alert("Asignatura Agregada");
                    //$("#btnCerrarModaCliente").click();
                    //$("#btnConsultar").click();
                },
                error: function (xhr) {
                    //alert("No se puede agregar, ya existe este número de cedula");
                }
            });
    });

</script>

SistemAcademico/Views/Asignatura/EditarAsignatura.cshtml
@model SistemAcademico.Models.AsignaturaModel

<div class="row">
    <div class="col-lg-3">
        <label asp-for="Nombre" class="col-lg-4"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    @*<div class="col-lg-3">
        <label class="col-lg-3">Profesor</label>
        @Html.DropDownListFor(model => model.IdProfesor, (SelectList)ViewBag.Profesor, new { @class = "form-control chosen-select" })
        <span asp-validation-for="IdProfesor" class="text-danger"></span>
    </div>

    <div class="col-lg-3">
        <label class="col-lg-3">Curso</label>
        @Html.DropDownListFor(model => model.IdCurso, (SelectList)ViewBag.Curso, new { @class = "form-control chosen-select" })
        <span asp-validation-for="IdCurso" class="text-danger"></span>
    </div>*@

    <div class="col-lg-3">
            <label asp-for="Descripcion" class="col-lg-4"></label>
            <input asp-for="Descripcion" class="form-control" />
            <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

    <div class="modal-footer">
            <button class="btn btn-sm btn-success" id="btnActualizarSeccion">
                <i class="glyphicon glyphicon-refresh"></i> Grabar
            </button>
            <button class="btn btn-sm btn-danger" id="btnCerrar" data-dismiss="modal" aria-hidden="true">
                <i class="glyphicon glyphicon-remove"></i> Cerrar
            </button>
    </div>
</div>

<script>

    function modeloAsignatura() {

        var modelo =
        {
            IdAsignatura: $('#IdAsignatura').val(),
            Nombre: $('#Nombre').val(),
            Descripcion: $('#Descripcion').val(),
        };

        return modelo;
    }

    $("#btnActualizarAsignatura").click(function () {

        var model = modeloAsignatura();

        $.ajax(
            {
                cache: false,
                type: 'POST',
                url: '@Url.Action("ActualizarAsignatura", "Asignatura")',
                data: model,
                success: function (data) {
                    alert("Asignatura modificada");
                    //$("#divListaArticulo").html('');
                    //$("#divListaArticulo").html(data);
                    //$("#btnCerrarModalCliente").click();
                    //$("#btnConsultar").click();
                },
                error: function (xhr) {
                    alert(xhr);
                    return false;
                }
            });
    });

</script>

SistemAcademico/Views/Asignatura/MantenimientoAsignatura.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>

@model IEnumerable<SistemAcademico.Models.AsignaturaModel>

<div class="editor-field col-lg-2">
    <button id="btnAgregarAsignatura" type="submit" class="btn btn-primary" data-toggle="modal" data-target="#ModalAgregarAsignatura">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar
    </button>
</div>

<table class="table" id="tblAsignaturas">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    <button class="btn btn-xs btn-primary"
                            id="btnEditarAsignatura"
                            data-prop="@item.IdAsignatura"
                            data-tooltip="tooltip"
                            title="Editar Asignatura!"
                            data-placement="top"
                            data-toggle="modal"
                            data-target="#ModalEditarAsignatura">
                        Editar
                    </button>

                    <button class="btn btn-xs btn-danger"
                            id="btnEliminarAsignatura"
                            data-prop="@item.IdAsignatura"
                            data-tooltip="tooltip"
                            data-placement="top"
                            title="Eliminar Asignatura!">
                        Eliminar
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="ModalAgregarAsignatura" tabindex="-1" role="dialog" aria-labelledby="myModalAgregarAsignatura">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="myModalAgregarAsignatura">Agregar Asignatura</h4>
            </div>
            <div id="divAgregarAsignatura">
                <div class="modal-body-trans">
                    Cargando...
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="ModalEditarAsignatura" tabindex="-1" role="dialog" aria-labelledby="myModalEditarAsignatura">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="myModalEditarAsignatura">Editar Asignatura</h4>
            </div>
            <div id="divEditarAsignatura">
                <div class="modal-body-trans">
                    Cargando...
                </div>
            </div>

        </div>
    </div>
</div>

<script>

    $("#btnAgregarAsignatura").click(function () {
        $.ajax(
            {
                cache: false,
                type: 'GET',
                url: '@Url.Action("AgregarAsignatura", "Asignatura")',
                success: function (data) {
                    $("#divAgregarAsignatura").html('');
                    $("#divAgregarAsignatura").html(data);
                },
                error: function (xhr) {
                    alert(xhr);
                    return false;
                },
                complete: function () {
                },
                beforeSend: function () {
                }
            });
    });

    $("#tblAsignaturas").on("click", "#btnEditarAsignatura", function ()
    {
        var idAsignaturas = $(this).attr('data-prop');
        var parametro = { idAsignatura: idAsignaturas };
            $.ajax(
                {
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("EditarAsignatura", "Asignatura")',
                    data: parametro,
                    success: function (data) {
                        $("#divEditarAsignatura").html('');
                        $("#divEditarAsignatura").html(data);
                    },
                    error: function (xhr) {
                        alert(xhr);
                        return false;
                    },
                    complete: function () {
                    },
                    beforeSend: function () {
                    }
                });
    });

    $("#tblAsignaturas").on("click", "#btnEliminarAsignatura", function ()
    {
        var prop = $(this).attr('data-prop');
        var datos = prop.split(',');
            $.ajax(
                {
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("EliminarAsignatura", "Asignatura")',
                    data: {
                        "idAsignatura": datos[0]
                    },
                    success: function (data) {
                        alert("Eliminado correctamente");
                        //$("#btnConsultar").click();
                    },
                    error: function (xhr) {
                        alert(xhr);
                        return false;
                    },
                    complete: function () {
                    },
                    beforeSend: function () {
                    }
                });
    });

    //$(document).ready(function () {
    //    $('#tblBodega').DataTable({
    //        "autoWidth": true,
    //        "searching": true,
    //        "pagingType": "full_numbers",
    //        "lengthMenu": [[5, 10, 15, -1], [5, 10, 15, "Todos"]],
    //        "language": {
    //            "sProcessing": "Procesando...",
    //            "sLengthMenu": "_MENU_ registros por página",
    //            "sZeroRecords": "No se encontraron resultados",
    //            "sEmptyTable": "Ningún dato disponible en esta tabla",
    //            "sInfo": "_END_ de _TOTAL_ registros",
    //            "sInfoEmpty": "Mostrando 0 registros",
    //            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
    //            "sSearch": "Buscar:",
    //            "sInfoThousands": ",",
    //            "sLoadingRecords": "Cargando...",
    //            "oPaginate": {
    //                "sFirst": "<<",
    //                "sLast": ">>",
    //                "sNext": ">",
    //                "sPrevious": "<"
    //            },
    //            "oAria": {
    //                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
    //                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    //            }
    //        }
    //    });
    //});
</script>