SistemAcademico/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemAcademico.Filters;
using SistemAcademico.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class AlumnoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoAlumno()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoAlumno", Code.Alumno.ConsultarAlumnos(null));
        }

        public IActionResult AgregarAlumno()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            ViewBag.CursoSeccion = Code.Curso.ConsultarCatalogoCursoSeccion();
            return PartialView();
        }

        public IActionResult GrabarAlumno(AlumnoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.GrabarALumno(model);
            return View("Index");
        }

        public IActionResult EditarAlumno(int idAlumno)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            var x = Code.Alumno.ConsultarAlumnosPorId(idAlumno);
            return PartialView("EditarAlumno", x);
        }

        public IActionResult ActualizarAlumno(AlumnoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.ActualizarAlumno(model);
            return MantenimientoAlumno();
        }

        public void EliminarAlumno(int idAlumno)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.EliminarAlumno(idAlumno);
        }
    }
}

SistemAcademico/Controllers/CursoSeccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemAcademico.Filters;
using SistemAcademico.Models;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class CursoSeccionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoCursoSeccion()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoCursoSeccion", Code.Curso.ConsultarCursoSeccion());
        }

        public IActionResult AgregarCursoSeccion()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            ViewBag.Curso = Code.Curso.ConsultarCatalogoCurso();
            ViewBag.Seccion = Code.Seccion.ConsultarCatalogoSeccion();
            return PartialView("AgregarCursoSeccion");
        }

        public IActionResult GrabarCursoSeccion(CursoSeccionModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Seccion.GrabarCursoSeccion(model);
            return PartialView("Index");
        }
    }
}

SistemAcademico/Views/CursoSeccion/AgregarCursoSeccion.cshtml
@model SistemAcademico.Models.CursoSeccionModel


    <div class="row">
        <div class="col-lg-12">
            <label asp-for="IdCurso" class="control-label">Curso</label>
            @Html.DropDownListFor(model => model.IdCurso, (SelectList)ViewBag.Curso, new { @class = "form-control chosen-select" })
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <label asp-for="IdSeccion" class="control-label">Sección</label>
            @Html.DropDownListFor(model => model.IdSeccion, (SelectList)ViewBag.Seccion, new { @class = "form-control chosen-select" })
        </div>
    </div>

    <div class="modal-footer">
        <button class="btn btn-sm btn-success" id="btnGrabarCursoSeccion">
            <i class="glyphicon glyphicon-refresh"></i> Grabar
        </button>
        <button class="btn btn-sm btn-danger" id="btnCerrar" data-dismiss="modal" aria-hidden="true">
            <i class="glyphicon glyphicon-remove"></i> Cerrar
        </button>
    </div>

<script>

    function modeloCursoSeccion()
    {
        var modelo =
        {
            IdCurso: $('#IdCurso').val(),
            IdSeccion: $('#IdSeccion').val(),
        };
        return modelo;
    }

    //function validarDatos() {
    //    var model = modeloProfesor();
    //    if (model.Nombres === "") {
    //        alert("Ingrese Nombre");
    //        return false;
    //    }

    //    if (model.Apellidos === "") {
    //        alert("Ingrese Apellidos");
    //        return false;
    //    }

    //    if (model.Cedula === "") {
    //        alert("Ingrese Cedula");
    //        return false;
    //    }
    //    return true;
    //};

    $("#btnGrabarCursoSeccion").click(function () {

        var model = modeloCursoSeccion();

        //datos = validarDatos();
        //if (!datos) {
        //    return false;
        //}

        $.ajax(
            {
                cache: false,
                type: 'POST',
                url: '@Url.Action("GrabarCursoSeccion", "CursoSeccion")',
                data: model,
                success: function () {
                    alert("Curso/Seccion Agregado");
                    //$("#btnCerrarModaCliente").click();
                    //$("#btnConsultar").click();
                },
                error: function (xhr) {
                    //alert("No se puede agregar, ya existe este número de cedula");
                }
            });
    });

</script>  

SistemAcademico/Views/CursoSeccion/MantenimientoCursoSeccion.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>

@model IEnumerable<SistemAcademico.Models.CursoSeccionModel>

<h1>Mantenimiento Curso/Seccion</h1>

<div class="editor-field col-lg-2">
    <button id="btnAgregarCursoSeccion" type="submit" class="btn btn-primary" data-toggle="modal" data-target="#ModalAgregarCursoSeccion">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar
    </button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Curso")
            </th>
            <th>
                @Html.DisplayName("Sección")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCurso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreSeccion)
                </td>
                <td>
                    <button class="btn btn-xs btn-primary"
                            id="btnEditarCursoSeccion"
                            data-prop="@item.IdCursoSeccion"
                            data-tooltip="tooltip"
                            title="Editar Sección!"
                            data-placement="top"
                            data-toggle="modal"
                            data-target="#ModalEditarCursoSeccion">
                        Editar
                    </button>

                    <button class="btn btn-xs btn-danger"
                            id="btnEliminarCursoSeccion"
                            data-prop="@item.IdCursoSeccion"
                            data-tooltip="tooltip"
                            data-placement="top"
                            title="Eliminar Sección!">
                        Eliminar
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="ModalAgregarCursoSeccion" tabindex="-1" role="dialog" aria-labelledby="myModalAgregarCursoSeccion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="myModalAgregarCursoSeccion">Agregar Curso/Seccion</h4>
            </div>
            <div id="divAgregarCursoSeccion">
                <div class="modal-body-trans">
                    Cargando...
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="ModalEditarCursoSeccion" tabindex="-1" role="dialog" aria-labelledby="myModalEditarCursoSeccion">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="myModalEditarCursoSeccion">Editar Curso/Seccion</h4>
            </div>
            <div id="divEditarCursoSeccion">
                <div class="modal-body-trans">
                    Cargando...
                </div>
            </div>

        </div>
    </div>
</div>

<script>

    $("#btnAgregarCursoSeccion").click(function () {
        $.ajax(
            {
                cache: false,
                type: 'GET',
                url: '@Url.Action("AgregarCursoSeccion", "CursoSeccion")',
                success: function (data) {
                    $("#divAgregarCursoSeccion").html('');
                    $("#divAgregarCursoSeccion").html(data);
                },
                error: function (xhr) {
                    alert(xhr);
                    return false;
                },
                complete: function () {
                },
                beforeSend: function () {
                }
            });
    });

    $("#tblAlumnos").on("click", "#btnEditarAlumno", function ()
    {
        var idAlumnos = $(this).attr('data-prop');
        var parametro = { idAlumno: idAlumnos };
            $.ajax(
                {
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("EditarAlumno", "Alumno")',
                    data: parametro,
                    success: function (data) {
                        $("#divEditarAlumno").html('');
                        $("#divEditarAlumno").html(data);
                    },
                    error: function (xhr) {
                        alert(xhr);
                        return false;
                    },
                    complete: function () {
                    },
                    beforeSend: function () {
                    }
                });
    });

    $("#tblAlumnos").on("click", "#btnEliminarAlumno", function ()
    {
        var prop = $(this).attr('data-prop');
        var datos = prop.split(',');
            $.ajax(
                {
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("EliminarAlumno", "Alumno")',
                    data: {
                        "idAlumno": datos[0]
                    },
                    success: function (data) {
                        alert("Eliminado correctamente");
                        //$("#btnConsultar").click();
                    },
                    error: function (xhr) {
                        alert(xhr);
                        return false;
                    },
                    complete: function () {
                    },
                    beforeSend: function () {
                    }
                });
    });

    //$(document).ready(function () {
    //    $('#tblBodega').DataTable({
    //        "autoWidth": true,
    //        "searching": true,
    //        "pagingType": "full_numbers",
    //        "lengthMenu": [[5, 10, 15, -1], [5, 10, 15, "Todos"]],
    //        "language": {
    //            "sProcessing": "Procesando...",
    //            "sLengthMenu": "_MENU_ registros por página",
    //            "sZeroRecords": "No se encontraron resultados",
    //            "sEmptyTable": "Ningún dato disponible en esta tabla",
    //            "sInfo": "_END_ de _TOTAL_ registros",
    //            "sInfoEmpty": "Mostrando 0 registros",
    //            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
    //            "sSearch": "Buscar:",
    //            "sInfoThousands": ",",
    //            "sLoadingRecords": "Cargando...",
    //            "oPaginate": {
    //                "sFirst": "<<",
    //                "sLast": ">>",
    //                "sNext": ">",
    //                "sPrevious": "<"
    //            },
    //            "oAria": {
    //                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
    //                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    //            }
    //        }
    //    });
    //});
</script>