SistemAcademico/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemAcademico.Filters;
using SistemAcademico.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class AlumnoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoAlumno()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoAlumno", Code.Alumno.ConsultarAlumnos(null));
        }

        public IActionResult AgregarAlumno()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            ViewBag.CursoSeccion = Code.Curso.ConsultarCatalogoCursoSeccion();
            return PartialView();
        }

        public IActionResult GrabarAlumno(AlumnoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.GrabarALumno(model);
            return View("Index");
        }

        public IActionResult EditarAlumno(int idAlumno)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            var x = Code.Alumno.ConsultarAlumnosPorId(idAlumno);
            return PartialView("EditarAlumno", x);
        }

        public IActionResult ActualizarAlumno(AlumnoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.ActualizarAlumno(model);
            return MantenimientoAlumno();
        }

        public void EliminarAlumno(int idAlumno)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Alumno.EliminarAlumno(idAlumno);
        }
    }
}

SistemAcademico/Controllers/CursoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemAcademico.Filters;
using SistemAcademico.Models;
using System.Collections.Generic;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class CursoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoCurso()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoCurso", Code.Curso.ConsultarCurso(null));
        }

        public IActionResult AgregarCurso()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            return PartialView("AgregarCurso");
        }

        public IActionResult GrabarCurso(CursoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Curso.GrabarCurso(model);
            return View("Index");
        }

        public IActionResult EditarCurso(int idCurso)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            var curso = Code.Curso.ConsultarCursoPorId(idCurso);
            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            return PartialView("EditarCurso", curso);
        }

        public IActionResult ActualizarCurso(CursoModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Curso.ActualizarCurso(model);
            return MantenimientoCurso();
        }

        public void EliminarCurso(int idCurso)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Curso.EliminarCurso(idCurso);
        }
    }
}

SistemAcademico/Controllers/ProfesorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemAcademico.Filters;
using SistemAcademico.Models;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class ProfesorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoProfesor()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return View("MantenimientoProfesor", Code.Profesor.ConsultarProfesores(null, null));
        }

        public IActionResult GrabarProfesor(ProfesorModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Profesor.GrabarProfesor(model);
            return View("Index");
        }

        public IActionResult AgregarProfesor()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            return PartialView("AgregarProfesor");
        }

        public IActionResult EditarProfesor(int idProfesor)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            var x = Code.Profesor.ConsultarProfesorPorId(idProfesor);
            return PartialView("EditarProfesor", x);
        }

        public IActionResult ActualizarProfesor(ProfesorModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Profesor.ActualizarProfesor(model);
            return MantenimientoProfesor();
        }

        public void EliminarProfesor(int idProfesor)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;
            Code.Profesor.EliminarProfesor(idProfesor);
        }
    }
}

SistemAcademico/Controllers/SeccionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemAcademico.Filters;
using SistemAcademico.Models;
using System.Collections.Generic;

namespace SistemAcademico.Controllers
{
    [Acceder]
    public class SeccionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MantenimientoSeccion()
        {
            HttpContext.Session.GetString("Usuario");
            HttpContext.Session.GetString("Menu");
            //HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            return View("MantenimientoSeccion", Code.Seccion.ConsultarSeccion(null));
        }

        public IActionResult GrabarSeccion(SeccionModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Seccion.GrabarSeccion(model);
            return PartialView("Index");
        }

        public IActionResult AgregarSeccion()
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            ViewBag.Curso = Code.Curso.ConsultarCatalogoCurso();
            return PartialView("AgregarSeccion");
        }

        public IActionResult EditarSeccion(int idSeccion)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            var seccion = Code.Seccion.ConsultarSeccionPorId(idSeccion);
            ViewBag.Profesor = Code.Profesor.ConsultarCatalogoProfesor();
            ViewBag.Curso = Code.Curso.ConsultarCatalogoCurso();
            return PartialView("EditarSeccion", seccion);
        }

        public IActionResult ActualizarSeccion(SeccionModel model)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Seccion.ActualizarSeccion(model);
            return MantenimientoSeccion();
        }

        public void EliminarSeccion(int idSeccion)
        {
            HttpContext.Session.GetString("Usuario");
            //var menu = HttpContext.Session.GetString("Menu");
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(menu);
            //ViewBag.Menu = sesionMenu;

            Code.Seccion.EliminarSeccion(idSeccion);
        }
    }
}

SistemAcademico/Views/Shared/_Layout.cshtml
@using SistemAcademico.Models;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemAcademico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemAcademico</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @{
            @using Microsoft.AspNetCore.Mvc;
            @using Microsoft.AspNetCore.Http;
            @using Newtonsoft.Json;
            @using System.Linq;
            @using System.Collections.Generic;
        }

        @if (Model != null)
        {
            @*@Context.Session.GetString("Menu");*@
            //var sesionMenu = JsonConvert.DeserializeObject<List<MenuModel>>(@Context.Session.GetString("Menu"));
            @foreach (MenuModel item in JsonConvert.DeserializeObject<List<MenuModel>>(@Context.Session.GetString("Menu")))
            {
                @Html.ActionLink(item.Mensaje, item.NombreAccion, item.NombreController, new { area = "" }, new { @class = "navbar-brand" })
            }

            @Html.ActionLink("Cerrar Session", "CerrarSession", "Login", new { area = "" }, new { @class = "navbar-brand" })
        }

                @*@if (Model != null)
                {
                    @foreach (MenuModel item in TempData["Menu"] as List<MenuModel>) 
                    {
                        @Html.ActionLink(item.Mensaje, item.NombreAccion, item.NombreController, new { area = "" }, new { @class = "navbar-brand" })
                    }

                    @Html.ActionLink("Cerrar Session", "CerrarSession", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }*@


            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                @*<ul class="navbar-nav flex-grow-1"> (@ViewBag.Menu))s
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Profesor" asp-action="MantenimientoProfesor">Profesores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="MantenimientoAlumno">Estudiantes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="MantenimientoCurso">Cursos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Seccion" asp-action="MantenimientoSeccion">Seccion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="CursoSeccion" asp-action="MantenimientoCursoSeccion">Curso/Seccion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura" asp-action="MantenimientoAsignatura">Asignatura</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Calificaciones" asp-action="Calificaciones">Calificaciones</a>
            </li>
        </ul>*@
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SistemAcademico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>